#sudo docker-compose build
#sudo docker-compose --project-name app-test -f docker-compose.yml up
#
# Create tag's for images
# docker tag shortener_app:latest fsimon/shortener-app:latest
# docker tag shortener_api:latest fsimon/shortener-api:latest
# docker tag shortener_redirect:latest fsimon/shortener-redirect:latest
#
version: '3'  
services:
  app:
    image: fsimon/shortener-app:latest
    build: ./shortener-app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "8081:2001"
  api:
    image: fsimon/shortener-api:latest
    build: ./shortener-api
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "8080:2000"
  redirect:
    image: fsimon/shortener-redirect:latest
    build: ./shortener-redirect
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "8082:2002"
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
volumes:  
  redis_data:
