version: '3'  
services:
  app:
    image: fsimon/shortner-app:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "3001:3001"
  api:
    image: fsimon/shortner-api:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "2000:2000"
  redirect:
    image: fsimon/shortner-redirect:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
volumes:  
  redis_data:
