module.exports = require('yargs')
  .usage('Usage: $0 [options]')
  .alias('u', 'url')
  .describe('u', 'Application URL')
  .default('u', 'http://127.0.0.1:2001')
  .alias('p', 'port')
  .describe('p', 'Port number for the Express application')
  .default('p', 2001)
  .help('h')
  .alias('h', 'help')
  .argv;
